# `numpy`

In [1]:
import numpy as np

## Как создать массив в `numpy`?

In [28]:
a = np.array(["1", 2, "汉"])
b = np.array([1, 2, 3], dtype=np.uint16)
c = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]], dtype=np.float128)

In [16]:
a

array(['1', '2', '汉'], dtype='<U1')

In [10]:
b

array([1, 2, 3], dtype=uint16)

In [11]:
c

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float128)

In [42]:
print(c.shape)

(2, 3)


In [43]:
print(c.dtype)

float128


### Чтобы не писать велосипеды для создания кастомных массивов есть:

In [19]:
np.zeros((2, 2)) # array of all zeroes

array([[0., 0.],
       [0., 0.]])

In [20]:
np.ones((1,2)) # array of all ones

array([[1., 1.]])

In [21]:
np.full((2,2), 42) # constant array

array([[42, 42],
       [42, 42]])

In [25]:
np.eye(3) # diagonal matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.random.randint(-10, 10, (2, 5)) # array of random elems

array([[-2,  8, -1,  4, -8],
       [ 9,  6,  0,  2, -1]])

## Индексирование и слайсы

In [46]:
a = np.random.randint(0, 100, size=(5, 10))
print(a)

[[ 2 83 50 11 46 76 76 94 45 62]
 [ 5 34 96 83  0 89 39 48  6 24]
 [53 67 31 59 28 85 48 79 96 47]
 [ 5 31 50 79 70 43 27 89 57 12]
 [40 24 54 13 80 10 53 14 78 61]]


In [47]:
a[0]

array([ 2, 83, 50, 11, 46, 76, 76, 94, 45, 62])

In [51]:
a[0, 1] # the same as a[0][1]

83

In [52]:
# Можно делать слайсы по осям. Получим 2-ой столбец матрицы:
a[:, 1]

array([83, 34, 67, 31, 24])

In [53]:
# выведем все элементы, кроме последнего, из предпоследнего столбца:
a[:-1, -2]

array([45,  6, 96, 57])

In [54]:
# а теперь каждый 2-ой элемент (начиная с 0-ого индекса) последней строчки:
a[-1, ::2]

array([40, 54, 80, 53, 78])

In [57]:
# каждый 2-ой элемент (начиная с 1-ого индекса) последней строчки:
a[-1, 1::2]

array([24, 13, 10, 14, 61])

In [56]:
# все четные элементы массива:
a[a > 0]

array([ 2, 83, 50, 11, 46, 76, 76, 94, 45, 62,  5, 34, 96, 83, 89, 39, 48,
        6, 24, 53, 67, 31, 59, 28, 85, 48, 79, 96, 47,  5, 31, 50, 79, 70,
       43, 27, 89, 57, 12, 40, 24, 54, 13, 80, 10, 53, 14, 78, 61])

In [68]:
# 1-ая и 5-ая строчки массива:
a[np.array([0, 4])]

array([[ 2, 83, 50, 11, 46, 76, 76, 94, 45, 62],
       [40, 24, 54, 13, 80, 10, 53, 14, 78, 61]])

### Для присваивания тоже работает!

In [70]:
a

array([[ 2, 83, 50, 11, 46, 76, 76, 94, 45, 62],
       [ 5, 34, 96, 83,  0, 89, 39, 48,  6, 24],
       [53, 67, 31, 59, 28, 85, 48, 79, 96, 47],
       [ 5, 31, 50, 79, 70, 43, 27, 89, 57, 12],
       [40, 24, 54, 13, 80, 10, 53, 14, 78, 61]])

In [72]:
a[1:-1, :] = 1
a

array([[ 2, 83, 50, 11, 46, 76, 76, 94, 45, 62],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [40, 24, 54, 13, 80, 10, 53, 14, 78, 61]])

In [74]:
a[:, 1:3] = np.arange(2)
a

array([[ 2,  0,  1, 11, 46, 76, 76, 94, 45, 62],
       [ 1,  0,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  0,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  0,  1,  1,  1,  1,  1,  1,  1,  1],
       [40,  0,  1, 13, 80, 10, 53, 14, 78, 61]])

## Операции с `np.array`

In [108]:
a = np.random.randint(low=0, high=100, size=(3, 4))
b = np.random.randint(low=0, high=100, size=(3, 4))
c = np.random.randint(low=0, high=100, size=4)
d = 42

print(f"a: {a}", end="\n\n")
print(f"b: {b}", end="\n\n")
print(f"c: {c}", end="\n\n")

a: [[32 26 92 74]
 [35 88 86 97]
 [82  3 17  2]]

b: [[80 97  1 91]
 [ 6 21 55 45]
 [22 33 84  8]]

c: [45 43 93 66]



In [87]:
print(a.reshape((2, 6))) # the same as a.shape = (1, 6)

[[ 3 91 76 76 87 21]
 [85 78 17 49 95 70]]


In [88]:
print(a.T)

[[ 3 87 17]
 [91 21 49]
 [76 85 95]
 [76 78 70]]


In [89]:
a + b

array([[  5, 190, 122,  83],
       [151,  76, 110, 135],
       [ 68,  58, 175, 140]])

In [90]:
a - b

array([[  1,  -8,  30,  69],
       [ 23, -34,  60,  21],
       [-34,  40,  15,   0]])

In [92]:
# какое это умножение?
a * b

array([[   6, 9009, 3496,  532],
       [5568, 1155, 2125, 4446],
       [ 867,  441, 7600, 4900]])

In [94]:
# а это?
a @ b.T

array([[13043, 11429, 12372],
       [ 6709, 13294, 16886],
       [ 9745, 10148, 13808]])

In [95]:
a / b

array([[ 1.5       ,  0.91919192,  1.65217391, 10.85714286],
       [ 1.359375  ,  0.38181818,  3.4       ,  1.36842105],
       [ 0.33333333,  5.44444444,  1.1875    ,  1.        ]])

In [96]:
a = np.array([[5, 4], [7, 8]])
for_pow = np.array([2, 3])

a ** for_pow

array([[ 25,  64],
       [ 49, 512]])

In [97]:
np.sqrt(b)

array([[1.41421356, 9.94987437, 6.78232998, 2.64575131],
       [8.        , 7.41619849, 5.        , 7.54983444],
       [7.14142843, 3.        , 8.94427191, 8.36660027]])

In [98]:
np.sum(b)

565

In [114]:
np.sum(b, axis=0)

array([108, 151, 140, 144])

In [99]:
np.min(a[0])

4

In [109]:
np.vstack([a, b])

array([[32, 26, 92, 74],
       [35, 88, 86, 97],
       [82,  3, 17,  2],
       [80, 97,  1, 91],
       [ 6, 21, 55, 45],
       [22, 33, 84,  8]])

In [110]:
np.hstack([a, b])

array([[32, 26, 92, 74, 80, 97,  1, 91],
       [35, 88, 86, 97,  6, 21, 55, 45],
       [82,  3, 17,  2, 22, 33, 84,  8]])

### Волшебный `np.vectorize`

In [100]:
pow_2 = lambda x: x ** 2

In [103]:
pow_2(np.array([2, 3, 4]))

array([ 4,  9, 16])

In [104]:
pow_2([2, 3, 4])

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [105]:
pow_2_vec = np.vectorize(pow_2)
pow_2_vec([2, 3, 4])

array([ 4,  9, 16])

### Немного про broadcasting

In [118]:
a + d

array([[ 74,  68, 134, 116],
       [ 77, 130, 128, 139],
       [124,  45,  59,  44]])

In [115]:
a + c

array([[ 77,  69, 185, 140],
       [ 80, 131, 179, 163],
       [127,  46, 110,  68]])

In [117]:
b - d

array([[ 38,  55, -41,  49],
       [-36, -21,  13,   3],
       [-20,  -9,  42, -34]])

#### Задание (*): с помощью `np.random.randint` создайте два массива (`x` и `y`) с элементами в диапазоне [-1000, 1000], размерами (12, 42) и (42, 12), соответственно. Найдите самое большое положительное нечетное число последнего столбца произведения матриц `x` и `y`.

In [127]:
x = np.random.randint(-1000, 1000, (12, 42))
y = np.random.randint(-1000, 1000, (42, 12))

tmp = (x @ y)[:, -1]
print(tmp[(tmp % 2 == 1) & (tmp > 0)].max())

2046873


### Задание: написать решалку линейных уравнений

In [ ]:
# Линейные уравнения можно решать следующим образом: Ax = y, где A-матрица. 
# A^(T)Ax=A^(T)y
# x=(A^(T)A)^(-1)A^(T)y
# давайте сделаем свою решалку таких уравнений
# HINT: np.linalg...

def solution_finder(A, y):
    return None

### Задание: решить систему методом [Крамера](https://ru.wikipedia.org/wiki/%D0%9C%D0%B5%D1%82%D0%BE%D0%B4_%D0%9A%D1%80%D0%B0%D0%BC%D0%B5%D1%80%D0%B0)

In [128]:
#TODO решить систему методом Крамера
#HINT: np.linalg.det

def cramer_solver(A, b):
    return None

---

# scipy.sparse

In [131]:
from scipy.sparse import csr_matrix
from sys import getsizeof

In [144]:
a = np.random.randint(0, 2, (1, 1_000_000))
print(getsizeof(a))

a_csr = csr_matrix(a)
print(getsizeof(a_csr))

8000112
56


In [145]:
a.mean()

0.499901

#### Или можно вот так вот создать:

In [149]:
values = list(range(1, 11))
row_idxs = [0, 1, 2, 0, 1, 2, 0, 1, 2, 3]
column_idxs = [4, 3, 2, 1, 1, 2, 3, 4, 0, 0]

csr_improvisation = csr_matrix((values, (row_idxs, column_idxs)))
csr_improvisation.toarray()

array([[ 0,  4,  0,  7,  1],
       [ 0,  5,  0,  2,  8],
       [ 9,  0,  9,  0,  0],
       [10,  0,  0,  0,  0]], dtype=int64)